# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project

# set RELATIVE to the next higher directory
# and defer to the appropriate Makefile.* there
RELATIVE := ..

include $(RELATIVE)/Makefile